#!/usr/bin/env python3


#-------------------------------------------------
# Create an IC file from an output file
# generated by the hydro code
#
# usage:
#   output_to_IC.py outputfile.out
#
# resulting IC file will be called 'restart.dat'
#-------------------------------------------------



from particle_hydro_utils import get_only_cmdlinearg
from particle_hydro_io import read_output, write_ic
from particle_hydro_plotting import plot_1D, plot_2D


if __name__ == "__main__":
    
    fname = get_only_cmdlinearg()
    ndim, x, m, rho, u, p, h, t, step = read_output(fname)
    write_ic("restart.dat", ndim, x, m, u, p)

